//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCollection.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Views_Home_Credits_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Views_Home_Credits_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppCollection.Resources.Views.Home.Credits.en", typeof(Views_Home_Credits_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main programmer: .
        /// </summary>
        internal static string Hlavní_programátor__ {
            get {
                return ResourceManager.GetString("Hlavní programátor: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspired by: .
        /// </summary>
        internal static string Inspirováno_aplikací__ {
            get {
                return ResourceManager.GetString("Inspirováno aplikací: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing, PR: .
        /// </summary>
        internal static string Marketing__ {
            get {
                return ResourceManager.GetString("Marketing: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation: .
        /// </summary>
        internal static string Překlad__ {
            get {
                return ResourceManager.GetString("Překlad: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testings: .
        /// </summary>
        internal static string Testování__ {
            get {
                return ResourceManager.GetString("Testování: ", resourceCulture);
            }
        }
    }
}
