//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCollection.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Views_Home_Clock_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Views_Home_Clock_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppCollection.Resources.Views.Home.Clock.en", typeof(Views_Home_Clock_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Time &amp; Weather.
        /// </summary>
        internal static string Aktuální_čas___počasí {
            get {
                return ResourceManager.GetString("Aktuální čas & počasí", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather information is not available..
        /// </summary>
        internal static string Informace_o_počasí_nejsou_dostupné_ {
            get {
                return ResourceManager.GetString("Informace o počasí nejsou dostupné.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City:.
        /// </summary>
        internal static string Město_ {
            get {
                return ResourceManager.GetString("Město:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather:.
        /// </summary>
        internal static string Počasí_ {
            get {
                return ResourceManager.GetString("Počasí:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weather icon.
        /// </summary>
        internal static string počasí_ikona {
            get {
                return ResourceManager.GetString("počasí ikona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature:.
        /// </summary>
        internal static string Teplota_ {
            get {
                return ResourceManager.GetString("Teplota:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind:.
        /// </summary>
        internal static string Vítr_ {
            get {
                return ResourceManager.GetString("Vítr:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity:.
        /// </summary>
        internal static string Vlhkost_ {
            get {
                return ResourceManager.GetString("Vlhkost:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Weather.
        /// </summary>
        internal static string Zobrazit_počasí {
            get {
                return ResourceManager.GetString("Zobrazit počasí", resourceCulture);
            }
        }
    }
}
