//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCollection.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Views_Home_Index_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Views_Home_Index_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppCollection.Resources.Views.Home.Index.en", typeof(Views_Home_Index_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And more....
        /// </summary>
        internal static string A_další____ {
            get {
                return ResourceManager.GetString("A další ...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string Administrátor {
            get {
                return ResourceManager.GetString("Administrátor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymous.
        /// </summary>
        internal static string Anonym {
            get {
                return ResourceManager.GetString("Anonym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safe document storage.
        /// </summary>
        internal static string Bezpečné_ukládání_dat {
            get {
                return ResourceManager.GetString("Bezpečné ukládání dat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What this web app can do:.
        /// </summary>
        internal static string Co_tato_webová_aplikace_umí_ {
            get {
                return ResourceManager.GetString("Co tato webová aplikace umí:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile info.
        /// </summary>
        internal static string Info_o_profilu {
            get {
                return ResourceManager.GetString("Info o profilu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization.
        /// </summary>
        internal static string Lokalizace_do_více_jazyků {
            get {
                return ResourceManager.GetString("Lokalizace do více jazyků", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal user.
        /// </summary>
        internal static string Normální_uživatel {
            get {
                return ResourceManager.GetString("Normální uživatel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string O_projektu {
            get {
                return ResourceManager.GetString("O projektu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Přehled {
            get {
                return ResourceManager.GetString("Přehled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logins and users.
        /// </summary>
        internal static string Přihlášení_a_správa_uživatelů {
            get {
                return ResourceManager.GetString("Přihlášení a správa uživatelů", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Botstrap and responsive layout.
        /// </summary>
        internal static string Responzivní_Bootstrap_rozhraní {
            get {
                return ResourceManager.GetString("Responzivní Bootstrap rozhraní", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User type:.
        /// </summary>
        internal static string Typ_uživatele__ {
            get {
                return ResourceManager.GetString("Typ uživatele: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        internal static string Uživatelské_jméno_ {
            get {
                return ResourceManager.GetString("Uživatelské jméno:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome, .
        /// </summary>
        internal static string Vítejte__ {
            get {
                return ResourceManager.GetString("Vítejte, ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prague public transport departures finder.
        /// </summary>
        internal static string Vyhledávání_odjezdů_PID {
            get {
                return ResourceManager.GetString("Vyhledávání odjezdů PID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic information.
        /// </summary>
        internal static string Základní_info_ {
            get {
                return ResourceManager.GetString("Základní info:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic information.
        /// </summary>
        internal static string Základní_informace {
            get {
                return ResourceManager.GetString("Základní informace", resourceCulture);
            }
        }
    }
}
