//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCollection.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Views_Home_Transport_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Views_Home_Transport_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppCollection.Resources.Views.Home.Transport.en", typeof(Views_Home_Transport_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No delay.
        /// </summary>
        internal static string Bez_zpoždění {
            get {
                return ResourceManager.GetString("Bez zpoždění", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessible.
        /// </summary>
        internal static string Bezbariérový {
            get {
                return ResourceManager.GetString("Bezbariérový", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Čas {
            get {
                return ResourceManager.GetString("Čas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure time (min).
        /// </summary>
        internal static string Čas_odjezdu__min_ {
            get {
                return ResourceManager.GetString("Čas odjezdu (min)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route number.
        /// </summary>
        internal static string Číslo_linky {
            get {
                return ResourceManager.GetString("Číslo linky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air-conditioning.
        /// </summary>
        internal static string Klimatizace {
            get {
                return ResourceManager.GetString("Klimatizace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route.
        /// </summary>
        internal static string Linka {
            get {
                return ResourceManager.GetString("Linka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string minut {
            get {
                return ResourceManager.GetString("minut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform.
        /// </summary>
        internal static string Nástupiště {
            get {
                return ResourceManager.GetString("Nástupiště", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform:.
        /// </summary>
        internal static string Nástupiště_ {
            get {
                return ResourceManager.GetString("Nástupiště:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop name:.
        /// </summary>
        internal static string Název_zastávky_ {
            get {
                return ResourceManager.GetString("Název zastávky:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departures PID.
        /// </summary>
        internal static string Odjezdy_PID {
            get {
                return ResourceManager.GetString("Odjezdy PID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        internal static string Směr {
            get {
                return ResourceManager.GetString("Směr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No current departures.
        /// </summary>
        internal static string Žádné_odjezdy_k_zobrazení {
            get {
                return ResourceManager.GetString("Žádné odjezdy k zobrazení", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string Zobrazit {
            get {
                return ResourceManager.GetString("Zobrazit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay.
        /// </summary>
        internal static string Zpoždění {
            get {
                return ResourceManager.GetString("Zpoždění", resourceCulture);
            }
        }
    }
}
